#!/usr/bin/env bash

# Send email to database list of addresses
# Author: Christopher Markieta

# Usage: ./group-mail database.sqlite3 'Email Subject Line'

if [ -z "$1" ]; then
	echo 'Missing argument for database file.'
	exit 1
elif [ -n "$3" ]; then
	echo 'Too many arguments specified.'
	echo 'Ensure argument 2 (email subject) is surrounded in quotes.'
	exit 3
fi

        IFS='|'           # Bash delimeter
     MY_DIR=$(dirname $0) # Directory of script
       body=$(sed -n '/Content-Type: multipart\/related;/,/<\/div>/p' original | head -n -1)
     footer=$(grep -A100000 '</html>' original | tail -n +2)
 recipients=$(sqlite3 "$MY_DIR/$1" "SELECT * FROM FSOSSCFP")
       from='FSOSS-CFP <fsoss-cfp@senecac.on.ca>'
unsubscribe='http://leapproject.ca/fsoss/unsubscribe' # Must be < 64 characters

if [ -n "$2" ]; then
	subject="$2"
else
	subject=$(grep 'Subject: ' original | head -1 | cut -d' ' -f2-)
fi

while read -r recipient; do
	read email id <<< "$recipient"

	sendmail $email <<-EOF
		to:$email
		subject:$subject
		from:$from
		$body
		<p style=3D"text-align:left">
		If you do not wish to receive further email regarding FSOSS, please
		<a href=3D"$unsubscribe
		?email=3D$(perl -MURI::Escape -e 'print uri_escape($ARGV[0]);' "$email")&id=
		=3D$id">click here to unsubscribe</a></p>
		</div>
		</body>
		</html>
		$footer
	EOF
done <<< "$recipients"
