#!/usr/bin/env bash

# Create SQLite3 database file for tracking subscription status
# Author: Christopher Markieta

if [ -z "$1" ]; then
    echo 'Missing argument for database name'
    echo 'Usage: ./mkdb database.sqlite3'
    exit 1
fi

sqlite3 "$1" '
CREATE TABLE SUBSCRIPTION
(
    ID         INTEGER  PRIMARY KEY, 
    EMAIL      TEXT     NOT NULL,
    SUBSCRIBED BOOLEAN  NOT NULL DEFAULT 1,
    DATE       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);'
