#!/usr/bin/env bash

if [ -z "$1" ]; then
    echo 'Missing argument for database name'
    echo 'Usage: ./mkdb database.sqlite3'
    exit 1
fi

sqlite3 "$1" '
CREATE TABLE SUBSCRIPTION
(
    EMAIL      TEXT     PRIMARY KEY,
    ID         INTEGER  NOT NULL DEFAULT (RANDOM()),
    SUBSCRIBED BOOLEAN  NOT NULL DEFAULT 1,
    DATE       DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);'
